// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1t9o7eCqvIZtne5JZaiJmGKpFQtnRMTY',
    appId: '1:751471598501:web:62692fedd45bf3a9ce664c',
    messagingSenderId: '751471598501',
    projectId: 'huruchat-2c9f9',
    authDomain: 'huruchat-2c9f9.firebaseapp.com',
    storageBucket: 'huruchat-2c9f9.firebasestorage.app',
    measurementId: 'G-RGFBF4641W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eteYvQNFRdp1Mw_X6pVcE9vQ_FR2bl4',
    appId: '1:751471598501:android:32459e763868ce40ce664c',
    messagingSenderId: '751471598501',
    projectId: 'huruchat-2c9f9',
    storageBucket: 'huruchat-2c9f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElHBbN66hUx6OP3nSC448VjLcrLJIJY4',
    appId: '1:751471598501:ios:8bcce56ba24e2ddace664c',
    messagingSenderId: '751471598501',
    projectId: 'huruchat-2c9f9',
    storageBucket: 'huruchat-2c9f9.firebasestorage.app',
    iosClientId: '751471598501-0a2b0mrkmrue22v4146hbqq172gknab5.apps.googleusercontent.com',
    iosBundleId: 'com.huruchat.huruchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElHBbN66hUx6OP3nSC448VjLcrLJIJY4',
    appId: '1:751471598501:ios:8bcce56ba24e2ddace664c',
    messagingSenderId: '751471598501',
    projectId: 'huruchat-2c9f9',
    storageBucket: 'huruchat-2c9f9.firebasestorage.app',
    iosClientId: '751471598501-0a2b0mrkmrue22v4146hbqq172gknab5.apps.googleusercontent.com',
    iosBundleId: 'com.huruchat.huruchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1t9o7eCqvIZtne5JZaiJmGKpFQtnRMTY',
    appId: '1:751471598501:web:de979197ab989fe9ce664c',
    messagingSenderId: '751471598501',
    projectId: 'huruchat-2c9f9',
    authDomain: 'huruchat-2c9f9.firebaseapp.com',
    storageBucket: 'huruchat-2c9f9.firebasestorage.app',
    measurementId: 'G-8BDJG6NTS3',
  );
}
