// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiTl0hnXRrvVIVJcD1kMKAyMx-SeuyItc',
    appId: '1:682244412177:web:7454d35eb49b4f3073f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    authDomain: 'friendapp-6ff9c.firebaseapp.com',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    measurementId: 'G-T3SV43E2VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcexcQgYTUF6znsQkliaNMKweOskbnn0',
    appId: '1:682244412177:android:8408bc9d83219d0a73f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBckMZhBAYWAJixF3NrvOk1mcW0gJ5KI1U',
    appId: '1:682244412177:ios:c2ded653a9216a7673f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    iosBundleId: 'com.huruchat.huruchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBckMZhBAYWAJixF3NrvOk1mcW0gJ5KI1U',
    appId: '1:682244412177:ios:c2ded653a9216a7673f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    iosBundleId: 'com.huruchat.huruchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiTl0hnXRrvVIVJcD1kMKAyMx-SeuyItc',
    appId: '1:682244412177:web:859d3f8a929fedef73f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    authDomain: 'friendapp-6ff9c.firebaseapp.com',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    measurementId: 'G-LY4JLVPY5V',
  );
}
